# Generated by Django 3.0 on 2019-12-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo_encoding',
            field=models.BinaryField(),
        ),
    ]
